### ISSUE TITLE
Prompt parser issues

### ISSUE THREAD

**Issue by crackfoo** [adieyal/sd-dynamic-prompts#142]
```
Error running process: C:\Users\crackers\sd\forks\auto1111\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "C:\Users\crackers\sd\forks\auto1111\modules\scripts.py", line 338, in process
    script.process(p, *script_args)
  File "C:\Users\crackers\sd\forks\auto1111\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 436, in process
    all_prompts = generator.generate(num_images)
  File "C:\Users\crackers\sd\forks\auto1111\extensions\sd-dynamic-prompts\prompts\generators\randomprompt.py", line 231, in generate
    prompts = self._generator.generate_prompts(self._template, max_prompts)
  File "C:\Users\crackers\sd\forks\auto1111\extensions\sd-dynamic-prompts\prompts\parser\random_generator.py", line 111, in generate_prompts
    prompts = list(tokens[0].prompts())
  File "C:\Users\crackers\sd\forks\auto1111\extensions\sd-dynamic-prompts\prompts\parser\random_generator.py", line 15, in prompts
    partials = [p.get_prompt() for p in self.tokens]
  File "C:\Users\crackers\sd\forks\auto1111\extensions\sd-dynamic-prompts\prompts\parser\random_generator.py", line 15, in <listcomp>
    partials = [p.get_prompt() for p in self.tokens]
  File "C:\Users\crackers\sd\forks\auto1111\extensions\sd-dynamic-prompts\prompts\parser\commands.py", line 19, in get_prompt
    prompts = list(self.prompts())
  File "C:\Users\crackers\sd\forks\auto1111\extensions\sd-dynamic-prompts\prompts\parser\random_generator.py", line 29, in prompts
    prompts = generator.generate_prompts(val, 1)
  File "C:\Users\crackers\sd\forks\auto1111\extensions\sd-dynamic-prompts\prompts\parser\random_generator.py", line 111, in generate_prompts
    prompts = list(tokens[0].prompts())
  File "C:\Users\crackers\sd\forks\auto1111\extensions\sd-dynamic-prompts\prompts\parser\random_generator.py", line 15, in prompts
    partials = [p.get_prompt() for p in self.tokens]
  File "C:\Users\crackers\sd\forks\auto1111\extensions\sd-dynamic-prompts\prompts\parser\random_generator.py", line 15, in <listcomp>
    partials = [p.get_prompt() for p in self.tokens]
  File "C:\Users\crackers\sd\forks\auto1111\extensions\sd-dynamic-prompts\prompts\parser\commands.py", line 20, in get_prompt
    return prompts[0]
IndexError: list index out of range
```

**To Reproduce**
the prompt gets converted properly maybe 20-30% of the time... so I guess it's not so simple to reproduce. Sometime 2 or 3 of the dynamic parts get converted and some don't.
I have a prompt setup like this:

`{__people/characters__|__people/customs__},__appearance/haircolour__ __appearance/hairstyle__ , __clothing/all_clothes__`

Just have Enable dynamic prompts checked

**Expected behaviour**
until just recently it was working as one would expect

**Comment by tusharbhutt** [comment]
I'm having issues with parentheses, braces, and brackets in the prompts as well.  For example, the prompt shift of [from:to:When] no longer works anything in the brackets are script file names.  Removing the brackets results in a successful prompt run, but not sure if it's then actually doing what's supposed to occur within the brackets, braces, or parentheses

**Comment by crackfoo** [comment]
Yeah seems these brackets and pipes etc... have gone awry. Also within my wildcard files, I have more of them in there too and some multiple within brackets... worked like a charm until recent updates... and perhaps its auto's updates that broke something? whats the built-in extension "prompt-bracket-checker" thats in auto1111? I've tried enabling and disabling it tho with no change

**Comment by Xenodimensional** [comment]
Ahhh wth... it worked last night. So frustrating when mistakes like this make it out the door :/

**Comment by adieyal** [comment]
Thanks for reporting. I made a big change to the parser. While it provides much more flexibility when crafting prompts, I expected some teething issues since I couldn't anticipate how everyone uses it. Please note down any prompts that break so that I can address them.

**Comment by Xenodimensional** [comment]
{2$$and$$X1 | X2 | X3} yields: X1andX1 (i.e. with no spaces)
{2$$X1 | X2 | X3} yields: XX,XX (i.e. with no spaces)
{X$$and$$__wildcard1__|__wildcard2__|__wildcard3__} = no spaces
{X$$and$$ __wildcard1__ | __wildcard2__ | __wildcard3__ } = still no spaces

**Comment by adieyal** [comment]
I've added basic pass through support for prompt editing in 1.5.7, i.e. [a:b:when] should be left unchanged - I'll look into the examples you just provided.

**Comment by adieyal** [comment]
Just had a look at your examples, the separator is one of the only places where whitespace is significant. The default separator is `,`, which is equivalent to `{2$$,$$X1|X2|X3}`. 

If you want spaces, you can do something like `{2$$, $$X1|X2|x3}`. 
Using `and` as a separator - `{2$$ and $$X1|X2|X3}`

whitespace between variants is ignored, i.e. the following are all equivalent

`{2$$,$$X1|X2|X3}`
`{2$$,$$X1 |X2|X3}`
`{2$$,$$ X1| X2 | X3 }`


`

**Comment by r7vz9h3** [comment]
Compared to `v1.4.4`, `v1.5.7` breaks WebUI's native `[low emphasis]` syntax. Prompt gets cut off at the first `[`. So
`{apple|orange} __color__ [low emphasis] testing __color__` may give
`orange Royal blue \(dark\)`, throwing no errors but cutting off everything after `[`.
`(low emphasis:0.9)` can be used instead, but ideally the extension would leave vanilla WebUI's syntax alone.

Now, if a line with `[]` is selected from a wildcards file, it will throw the `list index out of range` error and won't process the prompt. I made a tiny wildcard file to test, with three lines:
```
(grape)
apple
[orange]
```
If either of the first two is selected, everything goes fine, but if `[orange]` would be selected, it breaks and throws the error:
```
Error running process: C:\SD\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "C:\SD\modules\scripts.py", line 338, in process
    script.process(p, *script_args)
  File "C:\SD\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 436, in process
    all_prompts = generator.generate(num_images)
  File "C:\SD\extensions\sd-dynamic-prompts\prompts\generators\randomprompt.py", line 231, in generate
    prompts = self._generator.generate_prompts(self._template, max_prompts)
  File "C:\SD\extensions\sd-dynamic-prompts\prompts\parser\random_generator.py", line 111, in generate_prompts
    prompts = list(tokens[0].prompts())
  File "C:\SD\extensions\sd-dynamic-prompts\prompts\parser\random_generator.py", line 15, in prompts
    partials = [p.get_prompt() for p in self.tokens]
  File "C:\SD\extensions\sd-dynamic-prompts\prompts\parser\random_generator.py", line 15, in <listcomp>
    partials = [p.get_prompt() for p in self.tokens]
  File "C:\SD\extensions\sd-dynamic-prompts\prompts\parser\commands.py", line 19, in get_prompt
    prompts = list(self.prompts())
  File "C:\SD\extensions\sd-dynamic-prompts\prompts\parser\random_generator.py", line 29, in prompts
    prompts = generator.generate_prompts(val, 1)
  File "C:\SD\extensions\sd-dynamic-prompts\prompts\parser\random_generator.py", line 112, in generate_prompts
    generated_prompts.append(prompts[0])
IndexError: list index out of range
```
Or:
```
Error running process: C:\SD\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py
Traceback (most recent call last):
  File "C:\SD\modules\scripts.py", line 338, in process
    script.process(p, *script_args)
  File "C:\SD\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 436, in process
    all_prompts = generator.generate(num_images)
  File "C:\SD\extensions\sd-dynamic-prompts\prompts\generators\randomprompt.py", line 231, in generate
    prompts = self._generator.generate_prompts(self._template, max_prompts)
  File "C:\SD\extensions\sd-dynamic-prompts\prompts\parser\random_generator.py", line 111, in generate_prompts
    prompts = list(tokens[0].prompts())
  File "C:\SD\extensions\sd-dynamic-prompts\prompts\parser\random_generator.py", line 15, in prompts
    partials = [p.get_prompt() for p in self.tokens]
  File "C:\SD\extensions\sd-dynamic-prompts\prompts\parser\random_generator.py", line 15, in <listcomp>
    partials = [p.get_prompt() for p in self.tokens]
  File "C:\SD\extensions\sd-dynamic-prompts\prompts\parser\commands.py", line 19, in get_prompt
    prompts = list(self.prompts())
  File "C:\SD\extensions\sd-dynamic-prompts\prompts\parser\random_generator.py", line 29, in prompts
    prompts = generator.generate_prompts(val, 1)
  File "C:\SD\extensions\sd-dynamic-prompts\prompts\parser\random_generator.py", line 111, in generate_prompts
    prompts = list(tokens[0].prompts())
  File "C:\SD\extensions\sd-dynamic-prompts\prompts\parser\random_generator.py", line 15, in prompts
    partials = [p.get_prompt() for p in self.tokens]
  File "C:\SD\extensions\sd-dynamic-prompts\prompts\parser\random_generator.py", line 15, in <listcomp>
    partials = [p.get_prompt() for p in self.tokens]
  File "C:\SD\extensions\sd-dynamic-prompts\prompts\parser\commands.py", line 20, in get_prompt
    return prompts[0]
IndexError: list index out of range
```
(The part after `prompts = generator.generate_prompts(val, 1)` is different.)

**Comment by crackfoo** [comment]
> 

I think most of the problems with mine are that I use things like:  subject {|  wildcard {text1|text2}}

So like that it used to either give me a results of just "subject" or "subject wildcard text#"

So now whenever dynamic prompt chooses the empty part {|  it blows up. Essentially what I was doing was randomly adding the extras text or not at all... perhaps there's a better way but I'm not sure any more?

Thanks

**Comment by adieyal** [comment]
> > 
> 
> I think most of the problems with mine are that I use things like: `subject {|__wildcard__ {text1|text2}}`
> 
> So like that it used to either give me a results of just "subject" or "subject wildcard text#"
> 
> So now whenever dynamic prompt chooses the empty part {| it blows up. Essentially what I was doing was randomly adding the extra wildcard & text or not at all... perhaps there's a better way but I'm not sure any more?
> 
> Thanks

I need to think about how address empty fields, I was considering some sort of optional indicator, something like:

`subject {__wildcard__ {text1|text2}}?`

Where the `?` indicates that the matching chunk can be empty.

**Comment by silvermike83** [comment]
Ah, yeah - I have a lot of wildcards nested that include optional things with blanks around the separator.

**Comment by adieyal** [comment]
@r7vz9h3  low emphasis tags should now work in v1.5.10. There are still some loose ends that aren't being properly handled which I am working on.

**Comment by silvermike83** [comment]
Should I rework my old wildcard structure to get rid of blanks?

**Comment by adieyal** [comment]
> Should I rework my old wildcard structure to get rid of blanks?

Are they all of the form `{|A|B}`? If so, I just pushed a changed that should be able to handle them. The optional indicator is still needed, but for more complicated clauses.

Let me know if 1.5.13 works for you.

**Comment by crackfoo** [comment]
Updated but still doesn't seem to work, but the optional indicator... is that a `?` after a set of {} that contains an empty field?

**Comment by adieyal** [comment]
Sorry, I wasn't clear. This should work: `{|A|B}`. Is that what you tried?

I haven't implemented the optional indicator yet.

**Comment by crackfoo** [comment]
yeah didn't work

`__appearance/haircolour__ __appearance/hairstyle__ `

haircolour is just basic colours, one per line but the hair style is where it's not working, which looks like this:

`messy hair {|with __aesthetics\colours__ {highlights|streaks}}`

**Comment by crackfoo** [comment]
Hold that thought... testing with just that seems ok. let me complicate the prompt some more and see what happens

**Comment by crackfoo** [comment]
So it seems, on it's own the hair stuff works, but when I add another wildcard before it that also has empty fields, it get processed but breaks everything after it...

**Comment by adieyal** [comment]
Could you provide the exact example that doesn't work?

**Comment by silvermike83** [comment]
I'm in business, anyway, thanks!

**Comment by ChrisFab16** [comment]
I have the same issue:
Traceback (most recent call last):
  File "/mnt/e/code/stable-diffusion-webui/modules/scripts.py", line 338, in process
    script.process(p, *script_args)
  File "/mnt/e/code/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py", line 412, in process
    all_prompts = generator.generate(num_images)
  File "/mnt/e/code/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/generators/magicprompt.py", line 53, in generate
    prompts = self._prompt_generator.generate(*args, **kwargs)
  File "/mnt/e/code/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/generators/randomprompt.py", line 231, in generate
    prompts = self._generator.generate_prompts(self._template, max_prompts)
  File "/mnt/e/code/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/parser/random_generator.py", line 123, in generate_prompts
    prompts = list(tokens[0].prompts())
  File "/mnt/e/code/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/parser/random_generator.py", line 19, in prompts
    partials = [p.get_prompt() for p in self.tokens]
  File "/mnt/e/code/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/parser/random_generator.py", line 19, in <listcomp>
    partials = [p.get_prompt() for p in self.tokens]
  File "/mnt/e/code/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/parser/commands.py", line 19, in get_prompt
    prompts = list(self.prompts())
  File "/mnt/e/code/stable-diffusion-webui/extensions/sd-dynamic-prompts/prompts/parser/random_generator.py", line 32, in prompts
    val = random.choice(values)
  File "/home/cip/miniconda3/lib/python3.9/random.py", line 346, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range



prompt:

__adjectives__,__all_nationalities__,__artmovement__,__quality__

**Comment by adieyal** [comment]
The reason why that's happening is that you don't have one or more of those wildcard files in your wildcards folder. The extension isn't handling it gracefully though - perhaps it should just ignore that wildcard and return it as is instead.

**Comment by ChrisFab16** [comment]
> The reason why that's happening is that you don't have one or more of those wildcard files in your wildcards folder. The extension isn't handling it gracefully though - perhaps it should just ignore that wildcard and return it as is instead.
> 
> Should be fixed in 1.5.17

ok - that failed gracefully previously. 
Thanks

**Comment by adieyal** [comment]
I'm going to close this issue as I think all parser issues have been addressed in v2.0.4  - please open a new issue if something else crops up
