### ISSUE TITLE
No values found for wildcards on Windows

### ISSUE THREAD

**Issue by Evighedspanda** [adieyal/sd-dynamic-prompts#354]
**Describe the bug**
All wildcards come back with "No values found for wildcard"
![beauty](https://user-images.githubusercontent.com/129301069/228571726-2fb929df-9e05-442a-b872-e69361480983.png)

**To Reproduce**
Steps to reproduce the behaviour, include the prompt you used if applicable:
1. txt2img - Only thing selected is dynamic prompt, 20 steps, CFG: 7, 512x512, 1 batch. Euler.
2. Tried with different promps and wildcards. Same results. Tried putting the wildcards in the collections and in the wildcards folder. Same result. 
![wildcard standard](https://user-images.githubusercontent.com/129301069/228571738-8c062d66-fd6b-498c-ad63-01321877147f.png)
3. The prompt chosen here is just the standard prompt from the Clarity model: a photorealistic full body photo, of __beauty__, wearing cowgirl outfit, daisy dukes, standing in front of old western tavern, Caucasian, toned physique, blonde hair, sensual look, natural breasts, large ass, (with a big iron on her hip), photographed on a Kodak box camera, (highly detailed:1.2), Award-winning photograph, wild-wild-west
4. If i go to Wildcard Manager and press any .txt, including the ones included with the extention, i get the following: # Failed to load file
![wildcard manager](https://user-images.githubusercontent.com/129301069/228571741-c7161b3f-2c1a-43a6-bd21-0be804926439.png)

**Are you using a local install or a colab?**
Local

**Expected behaviour**
It was working earlier. Dont know if updates ruined it or something else. 

**Additional context**
I had a1111 on auto update so it updated at some point and i did install some extensions
![extension](https://user-images.githubusercontent.com/129301069/228571730-7d5729df-d52a-4a60-a07c-73d2f0d673ad.png)

Im pretty new to this and to github, so I hope that i wrote it correctly.

**Comment by razvan-nicolae** [comment]
Perhaps related I get a similar problem on fresh addon install after populating wildcards folder
![image](https://user-images.githubusercontent.com/19169014/228575110-8cd1e4d6-72d7-4be9-8f88-e071f2b9e381.png)

**Comment by razvan-nicolae** [comment]
example log of the error - 'martiantourist\\Wildcards\\entity_queen'
Traceback (most recent call last):
  File "I:\SD\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\ui\wildcards_tab.py", line 224, in receive_tree_event
    wf = wildcard_manager.get_file(event["name"])
  File "I:\SD\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\wildcards\wildcard_manager.py", line 102, in get_file
    return self.tree.get_collection(name)
  File "I:\SD\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\wildcards\tree\tree.py", line 41, in get_collection
    return self.map[path]
KeyError: 'martiantourist\\Wildcards\\entity_queen'
'martiantourist\\Wildcards\\adj_magical'

**Comment by Evighedspanda** [comment]
I did a fresh install as well. 
  File "D:\a1111 backup\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\ui\wildcards_tab.py", line 224, in receive_tree_event
    wf = wildcard_manager.get_file(event["name"])
  File "D:\a1111 backup\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\wildcards\wildcard_manager.py", line 102, in get_file
    return self.tree.get_collection(name)
  File "D:\a1111 backup\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\wildcards\tree\tree.py", line 41, in get_collection
    return self.map[path]
KeyError: 'devilkkw\\audio\\audio_instruments_keyboard'
'devilkkw\\audio\\audio_genre'
Traceback (most recent call last):
  File "D:\a1111 backup\stable-diffusion-webui\extensions\sd-dynamic-prompts\sd_dynamic_prompts\ui\wildcards_tab.py", line 224, in receive_tree_event
    wf = wildcard_manager.get_file(event["name"])
  File "D:\a1111 backup\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\wildcards\wildcard_manager.py", line 102, in get_file
    return self.tree.get_collection(name)
  File "D:\a1111 backup\stable-diffusion-webui\venv\lib\site-packages\dynamicprompts\wildcards\tree\tree.py", line 41, in get_collection
    return self.map[path]
KeyError: 'devilkkw\\audio\\audio_genre'

**Comment by razvan-nicolae** [comment]
appears to be exactly same error as mine. hopefully we can get some feedback 👍

**Comment by adieyal** [comment]
Looking into it....

**Comment by adieyal** [comment]
The errors that you're posting look like the came from the wildcards tab. Could you check to see if there are errors when you try a prompt with a wildcard?

**Comment by Evighedspanda** [comment]
> The errors that you're posting look like the came from the wildcards tab. Could you check to see if there are errors when you try a prompt with a wildcard?

There is. The first screenshot is when I add to the prompt. It says No values found for wildcard and creates the prompt without the wildcard

**Comment by akx** [comment]
Ah, darn, I think this is a Windows-specific issue (judging from the backslashes).

**Comment by Evighedspanda** [comment]
> Ah, okay, yeah, the `os.sep` work we did in [adieyal/dynamicprompts#4](https://github.com/adieyal/dynamicprompts/pull/4) didn't quite pan out for Windows with New Wildcards; will be fixed by [adieyal/dynamicprompts#65](https://github.com/adieyal/dynamicprompts/pull/65)...

I can apply this fix or will it get updated later? Im a bit new at this

**Comment by akx** [comment]
@Evighedspanda 
If you want to apply it _right now_ to give it a whirl before it's merged and updated, you can try run

```
pip install https://github.com/akx/dynamicprompts/archive/ddd9755c29031175f6f8954dfb2606d2b8495e28.zip
```
in your environment.

**Comment by akx** [comment]
This is fixed with https://github.com/adieyal/sd-dynamic-prompts/commit/cc818087a5d2a21fd8a17df396ed3e2c6133ef99 (`sd-dynamic-prompts` 2.9.1). Sorry for the trouble!

**Comment by tusharbhutt** [comment]
Interesting... I am still having the issue on Windows where wildcard files are not seen in subfolders and I am one version a44ab94d loaded on Mon Apr 3 21:37:15 2023
