### ISSUE TITLE
Bug: new prompt not generated for each image

### ISSUE THREAD

**Issue by MrUrzza** [adieyal/sd-dynamic-prompts#484]
Dynamic prompts is only generating a single prompt for my image batches, no matter what boxes I select. Also of note, it doesn't generate new prompts even if I select "Combinatorial generation." For example, running a prompt of {red|blue}{cat|dog} with a depth of 4 will just give me 4 red cats. I am running this in automatic1111. I've tried deleting the extensions folder and reinstalling this extension, updating A1111.

**Comment by maestrodamus** [comment]
Do try again as this same problem, which only surfaced yesterday, seems to have been fixed somehow, at least in my case. The prompts during batch processing are not repeating anymore; there be randomness again! I've got vladmendic's SD.NEXT automatic1111 fork, more specifically version d1ab205d.

**Comment by adieyal** [comment]
@SteMoeller @MrUrzza can you confirm if your problem has been resolved?

**Comment by SteMoeller** [comment]
No, bug still exists...Just deleted everything and reinstalled. I even tried to manally update dynamic-prompts from the installed 0.25.2 to 0.27 (by changing the pyproject.toml) but that didn't help either. 
If I create one image after another the prompt is random. If I use batch size > 1 or batch count > 1 or combinatorial generation (no matter what numbers) all prompts are the same. This is also the case for the csv files written if enabled: prompt is identical for ALL images.

**Comment by adieyal** [comment]
I can't re-create this issue. Are there any useful messages in the terminal? Are you using a colab or are you running locallly?

**Comment by SteMoeller** [comment]
I am running locally... Can I add some kind of logging messages to the underlying dynamic-prompts python files to find the place where the "selection" of the prompts take place?

**Comment by SteMoeller** [comment]
The problem seems to be a general one... even when I use the example "A diamond ring set on a {gold|platinum} band." I get the following identical prompts in the csv file: 

positive_prompt,negative_prompt

A diamond ring set on a {gold|platinum} band.,

A diamond ring set on a gold band.,

A diamond ring set on a gold band.,

)

**Comment by MrUrzza** [comment]
@adieyal It was working in Vlad 1111, even when it was not in Automatic 1111. Looks like its working in automatic now.

**Comment by MrUrzza** [comment]
Now it appears to be broken in vlad, with the variables not being assigned. Meta data in the images for the prompt {red|green}{dog|cat} comes back with  {red|green}{dog|cat}, not something like red dog. The following error appears in cmd on startup. This just start to happen when I updated sd dynamic prompts


```
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\Urzza\automatic\extensions\sd-dynamic-prompts\install.py:21 in get_requirements                              │
│                                                                                                                     │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
FileNotFoundError: requirements.txt not found.

The above exception was the direct cause of the following exception:

┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\Urzza\automatic\modules\scripts.py:246 in wrap_call                                                          │
│                                                                                                                     │
│   245 │   try:                                                                                                      │
│ > 246 │   │   res = func(*args, **kwargs)                                                                           │
│   247 │   │   return res                                                                                            │
│                                                                                                                     │
│ C:\Users\Urzza\automatic\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py:106 in ui              │
│                                                                                                                     │
│   105 │   │   callbacks.register_pnginfo_saver(self._pnginfo_saver)                                                 │
│ > 106 │   │   callbacks.register_prompt_writer(self._prompt_writer)                                                 │
│   107 │   │   callbacks.register_on_infotext_pasted(self._pnginfo_saver)                                            │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│                                                                                                                     │
│ C:\Users\Urzza\automatic\extensions\sd-dynamic-prompts\install.py:73 in get_dynamic_prompts_version                   │
│                                                                                                                     │
│                                                                                                                     │
│ C:\Users\Urzza\automatic\extensions\sd-dynamic-prompts\install.py:31 in get_requirements                              │
│                                                                                                                     │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Exception: Failed to parse requirements file.
Create LRU cache (max_size=16) for preprocessor results.
16:56:02-430461 ERROR    Calling script:
                         C:\Users\Urzza\automatic\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py/ui:
                         Exception
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\Urzza\automatic\extensions\sd-dynamic-prompts\install.py:21 in get_requirements                              │
│                                                                                                                     │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
FileNotFoundError: requirements.txt not found.

The above exception was the direct cause of the following exception:

┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\Urzza\automatic\modules\scripts.py:246 in wrap_call                                                          │
│                                                                                                                     │
│   245 │   try:                                                                                                      │
│ > 246 │   │   res = func(*args, **kwargs)                                                                           │
│   247 │   │   return res                                                                                            │
│                                                                                                                     │
│ C:\Users\Urzza\automatic\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py:106 in ui              │
│                                                                                                                     │
│   105 │   │   callbacks.register_pnginfo_saver(self._pnginfo_saver)                                                 │
│ > 106 │   │   callbacks.register_prompt_writer(self._prompt_writer)                                                 │
│   107 │   │   callbacks.register_on_infotext_pasted(self._pnginfo_saver)                                            │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│                                                                                                                     │
│ C:\Users\Urzza\automatic\extensions\sd-dynamic-prompts\install.py:73 in get_dynamic_prompts_version                   │
│                                                                                                                     │
│                                                                                                                     │
│ C:\Users\Urzza\automatic\extensions\sd-dynamic-prompts\install.py:31 in get_requirements                              │
│                                                                                                                     │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Exception: Failed to parse requirements file.
```

**Comment by MrUrzza** [comment]
Found a copy of requirements.txt and put it into sd-dynamic-prompts. Fixed the error, but not sure why it was missing. Died after updating via the webui. @adieyal
